extends: standard
plugins:
  - import
  - html
  - react
env:
  browser: true
  node: true
  es6: true
rules: 
  max-len: [1, 80, 2]
  no-console: ["warn"]
  no-alert: ["warn"]
  react/jsx-uses-react: ["error"]
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
  sourceType: "module"